name: Test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, rpi]

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!